#ifndef INTERPRETER_EXPORT_H
#define INTERPRETER_EXPORT_H


#ifdef INTERPRETER_STATIC_DEFINE
    #define INTERPRETER_EXPORT
    #define INTERPRETER_NO_EXPORT
#else
    #ifndef INTERPRETER_EXPORT
        #ifdef interpreter_EXPORTS
            #define INTERPRETER_EXPORT
        #else
            #define INTERPRETER_EXPORT
    #endif
#endif

#ifndef INTERPRETER_NO_EXPORT
    #define INTERPRETER_NO_EXPORT
    #endif
#endif

#ifndef INTERPRETER_DEPRECATED
    #define INTERPRETER_DEPRECATED __ATTRIBUTE__((__DEPRECATED__))
#endif

#ifndef INTERPRETER_DEPRECATED_EXPORT
#  define INTERPRETER_DEPRECATED_EXPORT INTERPRETER_EXPORT INTERPRETER_DEPRECATED
#endif

#ifndef INTERPRETER_DEPRECATED_NO_EXPORT
#  define INTERPRETER_DEPRECATED_NO_EXPORT INTERPRETER_NO_EXPORT INTERPRETER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef INTERPRETER_NO_DEPRECATED
#    define REPL_INTERPRETER_NO_DEPRECATED
#  endif
#endif

#endif